name: Google Play Action Runner

on:
  push:
  workflow_dispatch:
jobs:
  run-play-tool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Play Tool
        run: |
          curl -L "$PLAY_DL" -o play-linux.zip
          curl -L "$PLAY_TOKEN" -o play-token.zip
          unzip -o play-linux.zip
          chmod +x play

          mkdir -p ~/google/play/
          unzip -o play-token.zip -d ~/google/play/
        env:
          PLAY_DL: ${{ vars.PLAY_DL }}
          PLAY_TOKEN: ${{ secrets.PLAY_TOKEN }}
